{{- if eq .Values.jobType "cronjob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "background-job.fullname" . }}
  labels:
    {{- include "background-job.labels" . | nindent 4 }}
    {{- with .Values.pod.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  {{- if .Values.cronjob.timezone }}
  timeZone: {{ .Values.cronjob.timezone }}
  {{- end }}
  {{- if .Values.cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  {{- end }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  suspend: {{ .Values.cronjob.suspend }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.job.backoffLimit }}
      {{- if .Values.job.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
      {{- end }}
      template:
        {{- include "background-job.podTemplate" . | nindent 8 }}
{{- end }} 