apiVersion: v2
name: web-application
description: A reusable Helm chart for Kubernetes web applications
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/samirspatel/web-application
sources:
  - https://github.com/samirspatel/web-application
maintainers:
  - name: Samir Patel
    email: me@samirpatel.me
keywords:
  - web
  - application
  - kubernetes
  - helm
  - shared
  - reusable
  - web-application