# Default values for the application

# Name override options
nameOverride: "web-application"
fullnameOverride: "web-application"

# Deployment configuration
deployment:
  replicas: 1

  image:
    repository: crccheck/hello-world
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Pod annotations
  podAnnotations: {}

  # Additional labels
  labels: {}

  # Datadog service monitoring labels
  datadogLabels:
    enabled: true
    service: web-application
    version: "" # Will default to Chart.AppVersion if not set
    env: "local" # Will be set based on deployment environment
    team: "devops" # Team owning the service
    tags: {} # Additional custom tags

  # Probe configurations
  livenessProbe:
    enabled: true
    path: /
    port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    path: /
    port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1

# Service configuration
service:
  type: ClusterIP
  # The port that the service will be exposed on within the cluster
  # Other pods/services will use this port to communicate with this service
  port: 8000
  # The port that the container is listening on inside the pod
  # This is where your application actually runs and accepts connections
  targetPort: 8000

# Ingress configuration
ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: ""
    traefik.frontend.passHostHeader: "true"
  hosts:
    - host: web-application.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# ConfigMap configuration
configMap:
  enabled: false
  data: {}

# Secret configuration
secret:
  enabled: false
  data: {}

# Environment variables
env:
  - name: APP_NAME
    value: "hello-world"
  - name: APP_ENV
    value: "local"
