### Default values for the application

# Name override options
nameOverride: ""
fullnameOverride: ""

# Deployment configuration
deployment:
  replicas: 1
  
  image:
    repository: crccheck/hello-world
    tag: latest
    pullPolicy: Always
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Pod annotations
  podAnnotations: {}
  
  # Additional labels
  labels: {}

# Service configuration
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

# Ingress configuration
ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: ""
    traefik.frontend.passHostHeader: "true"
  hosts:
    - host: web-application.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# ConfigMap configuration
configMap:
  enabled: false
  data: {}

# Secret configuration
secret:
  enabled: false
  data: {}

# Environment variables
env:
  - name: APP_NAME
    value: "hello-world"
  - name: APP_ENV
    value: "local" 