name: Release Shared Helm Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Package Charts
        run: |
          mkdir -p .cr-release-packages
          mkdir -p .cr-index
          # Package the chart
          helm package charts/web-application -d .cr-release-packages/
          # Create or update the index
          helm repo index .cr-release-packages/ --url https://samirspatel.github.io/helm-shared
          # Copy the index to both locations
          cp .cr-release-packages/index.yaml .cr-index/index.yaml

      - name: Create Pages Directory
        run: |
          mkdir -p .cr-pages
          # Create a simple index.html
          echo "<html><head><title>Helm Chart Repository</title></head><body><h1>Helm Chart Repository</h1><p>Add this repository to Helm:</p><pre>helm repo add helm-shared https://samirspatel.github.io/helm-shared</pre></body></html>" > .cr-pages/index.html
          # Copy chart packages and index
          cp -R .cr-release-packages/* .cr-pages/
          # Debug: List contents
          echo "Contents of .cr-pages:"
          ls -la .cr-pages/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .cr-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 