name: Release Shared Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'  # Match any changes in charts directory
      - '.github/workflows/release.yaml'  # Also run when workflow file changes

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"  # Skip releases that already exist
          CR_PACKAGE_PATH: ".cr-release-packages"
          CR_INDEX_PATH: ".cr-index/index.yaml"
          CR_OWNER: "samirspatel"
          CR_GIT_REPO: "helm-shared"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"