name: Release Shared Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'  # Match any changes in charts directory
      - '.github/workflows/release.yaml'  # Also run when workflow file changes

permissions:
  contents: write
  pages: write
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Charts
        run: |
          # Create temporary directory for chart packages
          mkdir -p .cr-release-packages
          
          # Package each chart
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Packaging chart: $chart"
              helm package "$chart" -d .cr-release-packages/
            fi
          done

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Copy new chart packages
          cp .cr-release-packages/* gh-pages/
          cd gh-pages
          
          # Configure git in this directory
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
          # Generate new index.yaml or merge with existing
          if [ -f index.yaml ]; then
            helm repo index . --merge index.yaml --url https://github.com/samirspatel/helm-shared/raw/refs/heads/gh-pages/
          else
            helm repo index . --url https://github.com/samirspatel/helm-shared/raw/refs/heads/gh-pages/
          fi
          
          # Commit and push if there are changes
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updating Helm repository"
            git push origin gh-pages
          fi

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Generate Chart Versions Table
        run: |
          echo "# Helm Charts" > CHARTS.md
          echo "" >> CHARTS.md
          echo "| Chart | Version | App Version | Description |" >> CHARTS.md
          echo "|-------|---------|-------------|-------------|" >> CHARTS.md
          
          for chart in charts/*/Chart.yaml; do
            name=$(yq e '.name' "$chart")
            version=$(yq e '.version' "$chart")
            appVersion=$(yq e '.appVersion // "N/A"' "$chart")
            description=$(yq e '.description' "$chart")
            echo "| $name | $version | $appVersion | $description |" >> CHARTS.md
          done

          # Commit and push the updated CHARTS.md
          git add CHARTS.md
          if git diff --staged --quiet; then
            echo "No changes to CHARTS.md"
          else
            git commit -m "docs: update chart versions table"
            git push origin main
          fi
  